### PR TITLE
E-mail Welcome Message

### PR DESCRIPTION
**Pull request by bbspike**
Now the welcome message is taken from the database.
The message can be edit true the Sentora config module

### CODE REVIEW

**Comment by TGates71** [comment]
Need to also link this to the installer so the DB table is there.

**Comment by TGates71** [comment]
Never mind, just saw the request there too.

**Comment by Caffe1neAdd1ct** [comment]
Before i can pull this we need to look at implementing the database query securely through the bindQuery method.

I'll pull and fix the query method shortly.

**Comment by Caffe1neAdd1ct** [comment]
I think we should look at improving this request to store the welcome message on the reseller record so each can have different messages for their users at some point.

**Comment by TGates71** [comment]
That would be the better way Kev.

**Pull request merged**
