### PR TITLE
Allow HTML style in Notice

### PR DESCRIPTION
**Pull request by bbspike**
Allow HTML style in Notice

### CODE REVIEW

**Comment by bobsta63** [comment]
Just pointing out here that removing the xssClean() function/static method here would result in the ability to XSS attack but, I agree that as an administrator/reseller of the system you should be trusted to control the content of the box but for the elitist out there.... just making the point ;)

**Comment by Caffe1neAdd1ct** [comment]
If you offer reselling then you may not be able to "trust" the input coming from the resellers.. 

I would advise against this pull request due to security implications as Bobby also explained.

**Comment by bobsta63** [comment]
I fully agree - I would seriously consider rejecting this PR!

**Comment by bobsta63** [comment]
The only other thing that I would suggest (assuming you want styling on the reseller notices) is to allow Markdown parsing - that would offer a suitable mid-way solution wouldn't you agree @bbspike ?

**Comment by bbspike** [comment]
Could work yes. Or maybe drop de xssclean (not prevending it al) and use HTML - purifier?

**Comment by bobsta63** [comment]
I think Markdown would be better IMHO but I guess others may disagree - You could also implement a nice Markdown WYSIWIG editor too so the underlying syntax is abstracted etc and then of no concern to the user - Unless they want to use <marquee> tags lol and then they should be shot anyways ;)

**Comment by Caffe1neAdd1ct** [comment]
Parsing Markdown would be safer than trying to sanitise HTML.. not a bad idea :+1: 

I remember using https://github.com/erusev/parsedown before..

**Comment by TGates71** [comment]
Or, adjust it for admin only, not reseller.

**Comment by bbspike** [comment]
Thats a possibiltiy to:)
Stll don't get why Tinymc is intergrated do...Why styling in html input if the output is stripped.

**Comment by TGates71** [comment]
Erm... if using tinymce, then you disable the stripping and use it to do easy html...

**Comment by MBlagui** [comment]
Not good Notice will remain now without HTML.

**Pull request closed without merging**
