### PR TITLE
Using better regex for emails

### PR DESCRIPTION
**Pull request by jtomaszon**
The easiest and safest way to check whether an email address is well-formed is to use PHP's filter_var() function.

### CODE REVIEW

**Comment by TGates71** [comment]
Can also be used to sanitize email input:
```php
<?php
$email = "john.doe@example.com";

// Remove all illegal characters from email
$email = filter_var($email, FILTER_SANITIZE_EMAIL);

// Validate e-mail
if (!filter_var($email, FILTER_VALIDATE_EMAIL) === false) {
    echo("$email is a valid email address");
} else {
    echo("$email is not a valid email address");
}
?>
```

**Comment by TGates71** [comment]
My suggestion would be:
```php
     static function IsValidEmail($email)
     {
         // check for illegal characters
         if (!filter_var($email, FILTER_SANITIZE_EMAIL)) {
            // validate
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                return false;
            }
            return false;
         }
         return true;
```

**Comment by allebb** [comment]
You could simplify further and generally better practice (avoiding sub-IF statements) like so:

```php
static function IsValidEmail($email)
{
     if (!filter_var($email, FILTER_SANITIZE_EMAIL))
            return false;
    if (!filter_var($email, FILTER_VALIDATE_EMAIL))
                return false;
    return true;
}
```

**Comment by allebb** [comment]
Obviously Sentora isn't adhearing to PSR standards but normally I would use O/C braces too...

**Comment by TGates71** [comment]
Nice, and hi Bobby! I just threw that together for lack of knowledge but to get the idea across :)

**Comment by allebb** [comment]
It's cool - I just thought I throw in my recommendation and wanted to join in the convo ;)

**Comment by jtomaszon** [comment]
No actions?

**Comment by TGates71** [comment]
Went with Bobby's solution.

**Pull request closed without merging**
