### PR TITLE
Fix broken methods (see issue #333)

### PR DESCRIPTION
**Pull request by Bizarrus**

### CODE REVIEW

**Comment by TGates71** [comment]
What php version are you using? The FTP module has been working just fine on the current base installs of Sentora (php 5+)

**Comment by caglaroflazoglu** [comment]
Bugs:
http://forums.sentora.org/showthread.php?tid=10734

Yes, it fixed the blank ftp page bug for php7+

**Comment by caglaroflazoglu** [comment]
and another bug is here (500 error during delete)
**modules/ftp_management/code/controller.ext.php**

static function doDeleteFTP()
    {
        global $controller;
        runtime_csfr::Protect();
        $formvars = $controller->GetAllControllerRequests('FORM');
        if (**self::ExecuteDeleteFTP($formvars['inDelete']))**
            self::$ok = true;
        return true;
    }

static function ExecuteDeleteFTP(**$ft_id_pk, $uid**)
to 
static function ExecuteDeleteFTP(**$ft_id_pk, $uid=null**)

**Comment by Dukecitysolutions** [comment]
Fixed in v2.0.0 closing. Also, no issues with deleting FTP user account Found.

**Pull request closed without merging**
