### PR TITLE
Fix sub domain creation

### PR DESCRIPTION
**Pull request by kermitoo**

### CODE REVIEW

**Comment by MBlagui** [comment]
Never had issue with subdomains creations. Would you explain what's the issue here?

**Comment by kermitoo** [comment]
@MBlagui When you try to create a subdomain named subdomain.domain.com, domain.com is created instead.

**Comment by TGates71** [comment]
Are you using the sub domain manager or the domain manager? Sub domains have always worked for me also.

**Comment by kermitoo** [comment]
@TGates71 Sub domain manager

**Comment by CasteyDaSilva** [comment]
I've the same problem. On older version (1.0.1) works fine.

**Comment by MBlagui** [comment]
Before we can say this is bug, we need more infos to reproduce it.

Domain
OS
Update the panel to the latest release.

We can't fix what we can't reproduce.

**Comment by kermitoo** [comment]
@MBlagui Use the master branch for sentora-core and you should be able to reproduce it on any OS.
Go to the domains module, create a domain named domain.com for example, then go to the sub domain module and create subdomain.domain.com and you will see that that the sub domain will be named domain.com instead, which leads to a subdomain that does not work (not just a display error)

**Comment by CasteyDaSilva** [comment]
@kermitoo fix works well, thanks.

**Comment by TGates71** [comment]
Not sure how this would work since $subdomain is not set anywhere in the controller...?

**Comment by kermitoo** [comment]
@TGates71 Look at line 148

**Comment by TGates71** [comment]
Interesting. Mine does not have that. Totally different. This one has 483 lines, mine has 457...? Will compare the two...

**Comment by TGates71** [comment]
@MBlagui , I think we have an older version of the module. This fix works as intended if using this version.

**Pull request merged**
