### PR TITLE
Updated phpMyAdmin to 4.0.10.12

### PR DESCRIPTION
**Pull request by jacobgelling**
Tested and working on Ubuntu 12.04.

I noticed the installers currently config phpMyAdmin with http authentication, is this preferred over the normal login page?

### CODE REVIEW

**Comment by TGates71** [comment]
I had to change mine to the login page (personal preference). Not sure what others think.

**Comment by f00k** [comment]
I have changed the auth_type to "cookie" to be able to "Login As" to PhpMyAdmin straight from the MySQL Users page.

mysqlusers

To do this, I have customised **/etc/sentora/panel/modules/mysql_users/module.zpm** file and added:
```php
<a href="/etc/apps/phpmyadmin/index.php?pma_username=<& username &>&pma_password=<& dbpassword &>" class="btn btn-success" target="_blank"><: Login As :></a>
```
right before the line: (Line 131 for the version I am using)
```php
<button class="button-loader btn btn-default" type="submit" name="inEdit_<& userid &>" id="inEdit_<& userid &>" value="<& userid &>"><: Edit :></button>
```
Hope it makes your life easy too.

**Comment by eByte23** [comment]
DO NOT DO THIS!
THIS IS NOT SECURE!^^

**Comment by eByte23** [comment]
Please anyone correct me if I am wrong but the above code should not be used as a link.

When using a link regardless of http or https anyone can see the url so they could just copy and paste in and login, it will also be saved to your apache logs and also your browser history.

The same goes for http auth can be view by annon.

I could be completely wrong and you could be using some lovely code to make it secure but that would be my impression of just viewing the above.

**NOTE: this is not in regards to the upgrade its self
Elijah

**Comment by f00k** [comment]
@eByte23 - You're completely right Elijah.

For all of your concerns, PhpMyAdmin has a signon feature. I was too lazy to write 10 lines of extra code since I always use Private Window to login to my panel.

Signon feature is very easy to implement though, if you're interested to have or would like to contribute:

https://wiki.phpmyadmin.net/pma/Auth_types

**Comment by eByte23** [comment]
@f00k 
Ahh okay, sure yeah if you using if for your self and now really public facing cool!

Sure if I get bored over the weekend I could do that just need to wrap the details in a form and post to the index.php, but for http only connections anyone on the same network would easily be able to grab the data.

Elijah

**Comment by MBlagui** [comment]
Closing this BUT intersted in contribution over signon:

https://wiki.phpmyadmin.net/pma/Auth_types

If you can get it done right, it would be accepted.

**Comment by jacobgelling** [comment]
This pull request is simply a update to phpMyAdmin - it does not change auth type...

If you want to change auth type, you must do it with the installer.

**Comment by MBlagui** [comment]
I will handle the update thanks Jacob. I will update Roundcube too.

**Pull request closed without merging**
