### PR TITLE
We need to create logs in user directory aswell

### PR DESCRIPTION
**Pull request by michelsup**

### CODE REVIEW

**Comment by MBlagui** [comment]
We should wait for this update. we are in bug fixing mode here and apache_admin module is getting a total review soon. Agree allowing users access logs BUT we should ensure first he can't delete them!

M B

**Comment by 5050** [comment]
AMHO, user can delete his own logs at any time he want. There is still a copy in /var/sentora/logs for the admin.
I would be more afraid that some user never delete their logs, so they will fill the server space with it. I think it would be better to be an option to be activated on user request only.

**Comment by MBlagui** [comment]
good to be reviewed later with suEXEC.
Having logs in both sentora and user folder is not good, with duplicate files and apache ending up managing twice log files. 
Best solution is to set log fil in user folder with read only permission while log rotate will archive it and delete it later. User should not be able to delete his logs in case of abuse or hacker erase logs so we don't understand how he hacked the website.

M B

**Comment by tdonaldson-mpdc** [comment]
Just an idea...

What if you used a symbolic link from the users folder pointing to the admin version of the log, and re-generated it on DaemonRun. Saves the users storage allocation filling up with log data, and if the user wants to delete the link they can (won't benefit them at all to do so though). Would mean that under suEXEC that your log files would need to be readable by the user to have any benefit..

Alternatively, you could hold each users log files in a named directory and symlink that i.e. /var/sentora/hostdata/username/logs to /var/sentora/logs/username - same permissions issue would apply.

**Comment by MBlagui** [comment]
Will be implmented another way. We have better solution.

**Pull request closed without merging**
