### PR TITLE
Updated all copyright notices to 2019

### PR DESCRIPTION
**Pull request by VilhelmPrytz**
The title says it all :+1:.

### CODE REVIEW

**Comment by cantalupo555** [comment]
Unfortunately project is dead a long time

**Comment by 5050** [comment]
By the way, the better solution would be to remove the second date : the copyrigth starts at 2014, it have no reason to end at 2015, 2019 or any other year

**Comment by modcar** [comment]
I think there's more important updates for Sentora than copyright text. Php7 would be the place to start. Sent from Galaxy Note<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Pascal Peyremorte <notifications@github.com> </div><div>Date: 8/01/20  21:32  (GMT+12:00) </div><div>To: sentora/sentora-core <sentora-core@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Subject: Re: [sentora/sentora-core] Updated all copyright notices to 2019 (#329) </div><div>
</div>By the way, the better solution would be to remove the second date : the copyrigth starts at 2014, it have no reason to end at 2015, 2019 or any other year

**Comment by 5050** [comment]
Surely, but ... 
there is no longer people able to handle the project with enough amount of free time. 
I has more when I rewrote completely the installers and preconfig, when I ungraded modules and rewritten websites. But this was so time-eating that I spend to much time on it that it is reasonable for a free project.
And more, the project is now massively used to send spams or robbed to make commercial copies.
I'm tired of that.

**Comment by Dukecitysolutions** [comment]
> Surely, but ...
> there is no longer people able to handle the project with enough amount of free time.
> I has more when I rewrote completely the installers and preconfig, when I ungraded modules and rewritten websites. But this was so time-eating that I spend to much time on it that it is reasonable for a free project.
> And more, the project is now massively used to send spams or robbed to make commercial copies.
> I'm tired of that.

Hello @5050,
Sentora is a awesome product. Let me start by saying THANK YOU for everything you have done for the project. That said, I feel that you guys have given up. You cant say that NO ONE has any time to help. You guys refuse to let anyone other than your selves work on this project. 
Santora's Github is FULL of great PULL REQUESTS from others that want to help. You guys just don't seem to care about the community helping. 

I have a Sentora Live PHP 7.3 project almost ready and the Sentora team still hasn't even looked into it. All the PHP 7.3 work is done for you!!!

With all due respect, other people make commercial copies/renames of the Sentora project because you guys refuse to move the project forward. The whole CANT because Suhosin didn't support PHP 7.x I understand. That's not the case anymore with Snuffleupagus a Suhosin replacement. If any Sentora DEVS feel this way it might be time to move on and let someone that is passionate take your place.

**Pull request merged**
