### PR TITLE
Make the login page cloudflare friendly

### PR DESCRIPTION
**Pull request by kkprince1998**
This fixes Issue #177.

### CODE REVIEW

**Comment by TGates71** [comment]
@MBlagui

**Comment by kkprince1998** [comment]
Adding `data-cfasync="false"` to the script tags that control the anticlickjack and fade in ability causes them to load normally when cloudflare is active on sentora.

**Comment by MBlagui** [comment]
Good:

https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-

No impact but improve integration if you setup panel behind cloudflare.

**Comment by kkprince1998** [comment]
It certainly puzzled me why it wasn't working. Since rocket loader loads and executes scripts asynchronously, sometimes (or in this case, almost always) big scripts like jquery don't load before scripts that are dependant on it, and the scripts aren't executed in the traditional order, so it can break some scripts that don't even require jquery.

**Comment by 5050** [comment]
Hi,
As it is a for a specific environment (Cloudflare), and as there is also an alternative solution (see "Alternative" chapter on the cloudflare page linked above), I think it would be better to use it : 
if we update the panel sources to handle each particular case, we will go soon in a wall of thousands of "addons" that even may be incompatible each others or with some other environments.

**Comment by kkprince1998** [comment]
The Page rules are limited. 3 per domain on free accounts.

**Comment by kkprince1998** [comment]
Also, adding this mod is only really useful on scripts that need to be executed as the page loads. In addition, it is only required for the login page, because of the setup you have that fades in, and your 'anticlickjack' script.

Any js that is executed with some sort of event like onclick, is fine as long as the page is completely loaded first. I am using this fix on my production server, and all is good.

Adding this tag to jquery is only needed when another script that is executed as the page loads depends on it.

**Pull request closed without merging**
