### PR TITLE
Adding Vmail size directory

### PR DESCRIPTION
**Pull request by gurnadi**
By default, Usage viewer module in the dashboard was not included size of vmail directory, this code will include  size of vmail directory in the usage viewer module

### CODE REVIEW

**Comment by TGates71** [comment]
You need to update the code to use a prepared statement and bound parameters.
`$usersmail=$zdbh->query("SELECT DISTINCT vh_acc_fk,vh_name_vc FROM x_vhosts WHERE vh_acc_fk=$idmail");`
Should be something like:
```
            $usersmail = $zdbh->prepare("SELECT DISTINCT vh_acc_fk,vh_name_vc FROM x_vhosts WHERE vh_acc_fk=:idmail");
            $usersmail->bindParam(':dmail', $dmail);
            $usersmail->execute();
```
May need to be adjusted, just a quick reference.

**Comment by gurnadi** [comment]
@TGates71 thank you for your feedback.

**Comment by TGates71** [comment]
Testing fix. This should include the vmail folder size in the user's total disk space used.

**Comment by TGates71** [comment]
Manually added.

**Pull request closed without merging**
