### PR TITLE
added auto_dns function for subdomain

### PR DESCRIPTION
**Pull request by charan315**
DNS is automatically created for subdomain.

### CODE REVIEW

**Comment by CasteyDaSilva** [comment]
Good job, man. I'd like to see this in Sentora.
+1

**Comment by michelsup** [comment]
Yeah! Usefull.

**Comment by Ron-e** [comment]
i think i read somewhere that the philosophy of Sentora is to be modular and that to add this in the core  would go against this (combining 2 separate modules; dns manager and (sub) domains).
So it was suggested to make this in a separate (3th party) module which does this with a daemon hook..
I tried this but my coding skills are not up to that..
my failed ettamed to make a daemon hook -> https://github.com/Ron-e/MyDoodleBin/blob/master/dns%20less%20domain%20hook%20for%20sentora/OnDaemonRun.hook.php
Maybe in the same module to edit the default dns entries in table x_dns_create so they are editable in Sentora? (was my idea before it failed :stuck_out_tongue_closed_eyes: )

**Comment by 5050** [comment]
Yes, the idea is nice but must not be implemented this way for many reasons :

1) it make duplicate code between dns-management and sub-domain, with high risk of bug when a module is touched : any change in a module, like database structure update, may break the other, that is prohibited by convention.

2) we have already told internally (to be choosen) about enabling modular install without bind because many single user servers does not use bind (or should not) : because they use registrar dns or third party DNS (more secure, more robust), because single DNS server is not compliant, etc. 
With your change, Sub-Domain module will break if dns is not installed on the server.

I think the only way to implement a shared function between two modules it to implement a dedicated function in library (here in dryden directory) which may be called by all modules which require it.

**Pull request closed without merging**
