### PR TITLE
Feature/composer

### PR DESCRIPTION
**Pull request by trojanspike**
thoughts on starting to use composer to load class and PHP packages.?

### CODE REVIEW

**Comment by bobsta63** [comment]
Thanks for this Lee, I've actually already started the next version of Sentora of which already utilises Composer and PSR4 auto-loading.

As this is quite a major change to the existing framework, I personally prefer to leave this from the existing version in order to concentrate on the next release.

At present we are urgently trying to get this release stable and out the door, the implementation of composer is rather a large change for this version and something that I'm not comfortable with implementing this late on in the day.

I can share my personal repo with you later so you can see what I've been working on - a custom framework that feels similar to Laravel but a lot more leaner.

**Comment by trojanspike** [comment]
@bobsta63 Yea it is a huge change and would take time but worth it. It needs it's on branch for doing the change over.

Yea that would be awesome if you could share with me - thanks

**Comment by bobsta63** [comment]
In honesty I don't think it's worth doing on the current version of Sentora - Sentora, in it's current state is like the Anti-composer application (the way that classes are named for our own version of autoloading) lol...

 I think it would be better to concentrate on the new release rather than utilise a lot of time trying to fudge Composer support into 1.X.X as in theory (if done correctly) will break all existing 3rd party modules anyway, I think it is a better idea for us to build the next version around composer instead of trying to force composer on Sentora 1.x.x as I think it is a waste of time given that we could have 2.x.x out quicker.

**Comment by bobsta63** [comment]
@trojanspike I also just wanted to say that I'm not disputing what you've done (my posts above may look a little negative but not mean't like that at all buddy so sorry if they do)  and by all mean's if you want to work in a sepate branch to implement Composer support into this then feel free buddy... give us a shout when it's done and I'll check it out and if stable enough and is available before we release v2.x.x then we can consider merging to the master branch and releasing under v1.x.x

**Comment by trojanspike** [comment]
@bobsta63 :) no mate , your post wasn't negative at all. I can see where you're coming form - I'd be the same way ;) . If you have branch already I'd rather see it so I can get an idea of your plan so I can help along (if that makes sense) - same branch with a few heads on is can be better in the long run.

I also have plans for the API to take it up to date with REST/CRUD OAuth implemented etc - Composer would have made it easier . But again , a few heads would be better ;)

**Comment by sosojni** [comment]
Already working on new version? Damn nice! It came to me few times to ask about remaking Sentora in one of modern php frameworks (laravel / symphony / yii2 / something else) but it always felt like it's too early to ask when there is no even 1.0 stable verison out. If i may ask, why not Laravel or any other known framework? Why custom made? (asking this purely because i'm curious, not to debate what framework is better or to push certain framework or anything like that)

**Comment by denysvitali** [comment]
Could I be part of the private repo? I want to give an hand to the development if I can

**Comment by bobsta63** [comment]
Custom because although I'm a huge Laravel fan it would be easier for us to
maintain a custom framework rather than have to potentially make radical
changes every X months - eg. look at Laravel 4 and 5... L4 applications are
going to need a fair amount of work to get them to work in L5.

I feel that building a custom framework (that actually uses a lot of the
ideas and packages anyway form Laravel) means that it is far leaner and can
be far better tailored to our needs eg. better handling of a module centric
application. The CLI support in the new framework uses Symphony's Console
(the same as Laravel) and the ORM is using Eloquent too!

I know that 6 months down the line if I didn't decide to build a custom
framework (well really just bootstrapping the packages that Laravel uses
differently) then I'd regret it and wish I had given that a Web hosting
control panel isn't your everyday normal web app :)

Hope this makes sense :)

I'm not actually keen on giving too many people access to the private repo
at the moment as it just raises questions/generates emails and posts like
this and ultimately eats up my "spare" development time (and given that I
have a full-time job during the day also, that time ultimately isn't much
lol ;)) - I don't mean to sound like a knob but just the way it is and just
means that the speed at which the project evolves is slower than it could
be.

~ballen

**Comment by trojanspike** [comment]
I remember a few of us talking about this late last year - how time flies ;) . Laravel would be framework of choice but as you say , it changes alot. We would just need a similar work-flow for getting and managing packages we'd use in sentora - make it into it's own FrameWork. 

Good Docs etc

**Comment by bobsta63** [comment]
Closing PR as per discussion chain above. - Having a general clean-up of PR's before starting work on 1.1 release.

**Pull request closed without merging**
