### PR TITLE
Now Sentora will be faster due to Expire Headers.

### PR DESCRIPTION
**Pull request by alwaysontop617**

### CODE REVIEW

**Comment by MBlagui** [comment]
Caching is intersting. We will merge this.

**Comment by TGates71** [comment]
Testing on U14. So far so good! Has definitely sped things up.

**Comment by MrKaKisen** [comment]
But no merge yet? :)

**Comment by MBlagui** [comment]
done will need to added back to 1.0.4 branch manually or rebranch.

**Comment by BioALIEN** [comment]
@alwaysontop617 thank you, it's a good enhancement.
@MBlagui go ahead and cherry pick this into the 1.0.4 branch manually.

**Pull request merged**
